version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bugtracker-app
    restart: always
    env_file: .env
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: bugs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bugtracker.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  telegrambot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram-bot
    depends_on:
      - fastapi
      - redis
    env_file:
      - .env

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: queue-worker
    depends_on:
      - fastapi
      - redis
      - db
    env_file:
      - .env

volumes:
  pgdata:
