# Dockerfile.worker

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app
COPY .env .env

ENV PYTHONPATH=/app

CMD ["python", "app/queue_worker.py"]
